[program:comfyui]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/comfyui-start.sh
autostart=true
autorestart=true
startsecs=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
